# Generated by Django 2.2.8 on 2019-12-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191216_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrderTable',
            new_name='OrderProduct',
        ),
    ]
